import { LANDING_WP } from 'consts';
import { getDatabase, ref, onValue } from 'firebase/database';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useCallback, useContext, useEffect, useState } from 'react';
import Loader from '../components/common/Loader';
import { FirebaseContext } from '../components/context/firebase';
import ModalContext from '../components/context/modal';
import useSettings from '../components/hooks/useSettings';
import About from '../components/landingPage/About';
import Contact from '../components/landingPage/Contact';
import Footer from '../components/landingPage/Footer';
import Header from '../components/landingPage/Header';
import Portfolio from '../components/landingPage/Portfolio';
import Resume from '../components/landingPage/Resume';
import SidebarContainer from '../components/Sidebar/SidebarContainer';
// import styles from '../styles/Home.module.css';
import { MainPageContent } from '../types/mainPage';

const Home: NextPage = () => {
  const [resumeData, setResumeData] = useState<MainPageContent | null>();
  const fb = useContext(FirebaseContext);
  const { isEditing } = useSettings();

  const { openModal, setShow, modal } = useContext(ModalContext);
  useEffect(() => {
    openModal(() => <Loader />);
    const db = getDatabase(fb);
    const mainPageContent = ref(db, 'main-page-content');
    onValue(mainPageContent, (snapshot) => {
      const data = snapshot.val();
      setResumeData(data);
      setShow(false);
    });
  }, [fb]);

  const [waypoint, setWaypoint] = useState(LANDING_WP.HOME);
  const setWaypointCallback = useCallback((href: LANDING_WP) => {
    setWaypoint(href);
    history.pushState({}, '', '#' + href);
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {modal()}
      {resumeData && (
        <>
          {isEditing && <SidebarContainer data={resumeData} />}
          <div>
            <Header
              setWaypoint={setWaypointCallback}
              waypoint={waypoint}
              data={resumeData.main}
            />
            <About setWaypoint={setWaypointCallback} data={resumeData.main} />
            <Resume
              setWaypoint={setWaypointCallback}
              data={resumeData.resume}
            />
            <Portfolio
              setWaypoint={setWaypointCallback}
              data={resumeData.portfolio}
            />
            {/* <Testimonials
              setWaypoint={setWaypointCallback}
              data={resumeData.testimonials}
            /> */}
            <Contact setWaypoint={setWaypointCallback} data={resumeData.main} />
            <Footer data={resumeData.main} />
          </div>
        </>
      )}
    </div>
  );
};

export default Home;
