// import Testimonials from 'components/landingPage/Testimonials';
import { LANDING_WP } from 'consts';
import type { InferGetServerSidePropsType, NextPage } from 'next';
import Head from 'next/head';
import { useCallback, useContext, useState } from 'react';
import ModalContext from '../components/context/modal';
import useSettings from '../components/hooks/useSettings';
import About from '../components/landingPage/About';
import Contact from '../components/landingPage/Contact';
import Footer from '../components/landingPage/Footer';
import Header from '../components/landingPage/Header';
import Portfolio from '../components/landingPage/Portfolio';
import Resume from '../components/landingPage/Resume';
import SidebarContainer from '../components/Sidebar/SidebarContainer';
import { getData } from './api/data';

const Home: NextPage<InferGetServerSidePropsType<typeof getServerSideProps>> =
  ({ resumeData: data }) => {
    const [resumeData, setResumeData] = useState(data);
    const { isEditing } = useSettings();
    const { modal } = useContext(ModalContext);
    const [waypoint, setWaypoint] = useState(LANDING_WP.HOME);
    const setWaypointCallback = useCallback((href: LANDING_WP) => {
      setWaypoint(href);
      history.pushState({}, '', '#' + href);
    }, []);
    return (
      <div>
        <Head>
          <title>Ondrej Zeman home page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {modal()}
        {resumeData && (
          <>
            {isEditing && (
              <SidebarContainer
                data={resumeData}
                refreshData={(data) => {
                  setResumeData(data);
                }}
              />
            )}
            <div>
              <Header
                setWaypoint={setWaypointCallback}
                waypoint={waypoint}
                data={resumeData.main}
              />
              <About setWaypoint={setWaypointCallback} data={resumeData.main} />
              <Resume
                setWaypoint={setWaypointCallback}
                data={resumeData.resume}
              />
              <Portfolio
                setWaypoint={setWaypointCallback}
                data={resumeData.portfolio}
              />
              {/* <Testimonials
                setWaypoint={setWaypointCallback}
                data={resumeData.testimonials}
              /> */}
              <Contact
                setWaypoint={setWaypointCallback}
                data={resumeData.main}
              />
              <Footer data={resumeData.main} />
            </div>
          </>
        )}
      </div>
    );
  };

export async function getServerSideProps() {
  return {
    props: {
      resumeData: await getData(),
    },
  };
}

export default Home;
