# name: Deploy Application
# on: push
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     environment: PROD
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: "check is TEST_KEY exists"
#         env: 
#             super_secret: ${{ secrets.TEST_KEY }}
#         if: ${{ env.super_secret == '' }}
#         run: 'echo "echo the secret \"TEST_KEY\" has not been made; echo please go to \"settings \> secrets \> actions\" to create it"'